# Generated by Django 6.0.4 on 2026-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fertilizers/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
    ]
