# Generated by Django 6.0.4 on 2026-08-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0014_order_cancelled_at_order_expected_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
