# Generated by Django 6.0.4 on 2026-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0015_plant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Nursery', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('delivery_charge', models.FloatField(default=0)),
                ('free_delivery_above', models.FloatField(default=0)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('admin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('new_password', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
