# Generated by Django 6.0.4 on 2026-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0016_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='fertilizers/'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='fertilizers/'),
        ),
        migrations.AddField(
            model_name='pot',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pots/'),
        ),
        migrations.AddField(
            model_name='pot',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='pots/'),
        ),
    ]
