# Generated by Django 6.0.4 on 2026-08-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0017_fertilizer_image2_fertilizer_image3_pot_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='image3',
        ),
        migrations.CreateModel(
            name='FertilizerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fertilizers/')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_images', to='nursery.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='PotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pots/')),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_images', to='nursery.pot')),
            ],
        ),
    ]
