# Generated by Django 6.0.4 on 2026-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0019_alter_orderitem_order_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_plant',
        ),
        migrations.RemoveConstraint(
            model_name='wishlistitem',
            name='unique_wishlist_plant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(blank=True, choices=[('plant', 'Plant'), ('pot', 'Pot'), ('fertilizer', 'Fertilizer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_type',
            field=models.CharField(blank=True, choices=[('plant', 'Plant'), ('pot', 'Pot'), ('fertilizer', 'Fertilizer')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_type', 'product_id'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'product_type', 'product_id'), name='unique_wishlist_product'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='plant',
        ),
    ]
