# Generated by Django 6.0.4 on 2026-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0022_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='plant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(blank=True, choices=[('plant', 'Plant'), ('pot', 'Pot'), ('fertilizer', 'Fertilizer')], max_length=20, null=True),
        ),
    ]
