# Generated by Django 6.0.4 on 2026-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0023_remove_orderitem_plant_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(choices=[('plant', 'Plant'), ('pot', 'Pot'), ('fertilizer', 'Fertilizer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
